# Generated by Django 4.2.29 on 2026-03-20 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_queue', models.BooleanField(default=True)),
                ('can_access_patients', models.BooleanField(default=True)),
                ('can_access_doctors', models.BooleanField(default=True)),
                ('can_access_transactions', models.BooleanField(default=True)),
                ('can_access_reports', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
