# Generated by Django 4.2.29 on 2026-03-19 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_type', models.CharField(choices=[('new', 'New Patient'), ('existing', 'Existing Patient')], max_length=10)),
                ('payment_method', models.CharField(choices=[('selfpay', 'Self-Pay'), ('hmo', 'HMO / Insurance'), ('corporate', 'Corporate'), ('government_assistance', 'Government Assistance')], max_length=25)),
                ('hmo_provider', models.CharField(blank=True, max_length=100)),
                ('hmo_membership_id', models.CharField(blank=True, max_length=100)),
                ('corporate_company', models.CharField(blank=True, max_length=100)),
                ('government_program', models.CharField(blank=True, max_length=100)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/%d/')),
                ('queue_numbers', models.JSONField(default=dict)),
                ('kiosk_identifier', models.CharField(blank=True, max_length=50)),
                ('is_complete', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='services.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='patients.patient')),
                ('services', models.ManyToManyField(related_name='transactions', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='kiosk_trans_created_2ae827_idx')],
            },
        ),
    ]
