# Generated by Django 4.2.29 on 2026-03-19 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_queuecounter_currently_serving'),
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('processing', 'Processing'), ('done', 'Done'), ('no_show', 'No Show')], default='waiting', max_length=20)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='kiosk.transaction')),
            ],
            options={
                'ordering': ['arrived_at'],
                'indexes': [models.Index(fields=['service', 'queue_number'], name='kiosk_queue_service_bea238_idx')],
            },
        ),
    ]
