# Generated by Django 4.2.29 on 2026-03-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuecounter',
            name='currently_serving',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
